version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "thumbnail-rs"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-4l3ogookbzmg"
s3_prefix = "thumbnail-rs"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
